git_commit: d2d3efe
batch_size: 100
seed: 1742534068
system:
  flux: 5
  radius: null
  nspins:
  - 4
  - 0
  interaction_strength: 1.0
  lz_center: 0.0
  lz_penalty: 0.0
  l2_penalty: 0.0
  interaction_type: coulomb
network:
  type: pfaffian
  orbital: full
  psiformer:
    num_heads: 4
    heads_dim: 64
    num_layers: 2
    determinants: 1
  pfaffian:
    num_heads: 4
    heads_dim: 64
    num_layers: 2
mcmc:
  steps: 10
  width: 0.1
  burn_in: 500
  adapt_frequency: 200
optim:
  iterations: 1000
  optimizer: kfac
  adam:
    lr:
      rate: 0.001
      decay: 1.0
      delay: 2000.0
  kfac:
    lr:
      rate: 0.05
      decay: 1.0
      delay: 2000.0
log:
  save_path: null
  restore_path: null
  save_time_interval: 600
  save_step_interval: 1000
  initial_energy: true
